name: Run Optimizer

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # نصب تمام کتابخانه‌های مورد نیاز پروژه
          pip install pandas numpy scikit-learn psycopg2-binary ccxt joblib
          
      - name: Run Optimizer Script
        run: python src/optimizer.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          IS_GITHUB_ACTION: "true"

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ -n $(git status -s) ]]; then
            git add best_params.json
            git commit -m "Auto-update: Optimized trading parameters"
            git push
          else
            echo "No changes to commit."
          fi
